import type { paths } from "./types";

/** The JSON body of a response object generated by openapi-typescript. */
export type JsonBody<R> = R extends { content: { "application/json": infer B } } ? B : never;
/** The JSON body of a request object generated by openapi-typescript. */
export type JsonRequest<R> =
  NonNullable<R> extends { content: { "application/json": infer B } } ? B : never;

export type ErrorEnvelope = JsonBody<paths["/auth/login"]["post"]["responses"][401]>;
export type ErrorBody = ErrorEnvelope["error"];
export type ErrorCode = ErrorBody["code"];

export type Health = JsonBody<paths["/health"]["get"]["responses"][200]>["data"];

export type User = JsonBody<paths["/auth/me"]["get"]["responses"][200]>["data"]["user"];
export type ThemePreference = User["theme"];
export type UpdateMeBody = JsonRequest<paths["/auth/me"]["patch"]["requestBody"]>;
export type AuthSession = JsonBody<paths["/auth/login"]["post"]["responses"][200]>["data"];
export type LoginBody = JsonRequest<paths["/auth/login"]["post"]["requestBody"]>;
export type RegisterBody = JsonRequest<paths["/auth/register"]["post"]["requestBody"]>;
export type FeatureRequestSummary = JsonBody<
  paths["/feature-requests"]["get"]["responses"][200]
>["data"][number];

export type TaskListEnvelope = JsonBody<paths["/tasks"]["get"]["responses"][200]>;
export type TaskSummary = TaskListEnvelope["data"][number];
export type TaskDetail = JsonBody<paths["/tasks/{id}"]["get"]["responses"][200]>["data"];
export type Tag = JsonBody<paths["/tags"]["get"]["responses"][200]>["data"][number];

export type TaskStatus = TaskSummary["status"];
export type AiStatus = TaskSummary["aiStatus"];
export type AiSkipReason = NonNullable<TaskSummary["aiSkipReason"]>;
export type SuggestionState = NonNullable<TaskSummary["suggestionState"]>;

export type TaskListQuery = NonNullable<paths["/tasks"]["get"]["parameters"]["query"]>;
export type CreateTaskBody = JsonRequest<paths["/tasks"]["post"]["requestBody"]>;
export type UpdateTaskBody = JsonRequest<paths["/tasks/{id}"]["patch"]["requestBody"]>;
export type ReplaceTagsBody = JsonRequest<paths["/tasks/{id}/tags"]["put"]["requestBody"]>;
export type CreateTagBody = JsonRequest<paths["/tags"]["post"]["requestBody"]>;
export type UpdateTagBody = JsonRequest<paths["/tags/{id}"]["patch"]["requestBody"]>;
export type FeatureRequestBody = JsonRequest<paths["/feature-requests"]["post"]["requestBody"]>;
export type FeatureRequestResult = JsonBody<
  paths["/feature-requests"]["post"]["responses"][201]
>["data"];

/** The body of a response whose content is the SSE stream. openapi-typescript keys stream content
 *  by its media type exactly as it keys JSON, so the turn route's events are reachable from `paths`
 *  like every other model (spec 3.3). */
export type StreamBody<R> = R extends { content: { "text/event-stream": infer B } } ? B : never;

export type Conversation = JsonBody<
  paths["/feature-requests/conversation"]["get"]["responses"][200]
>["data"];
export type ConversationMessage = Conversation["messages"][number];
export type FeatureRequestDraft = Conversation["draft"];
export type RubricScore = NonNullable<Conversation["score"]>;
export type ConversationTurnBody = JsonRequest<
  paths["/feature-requests/conversation/{id}/messages"]["post"]["requestBody"]
>;
/** The discriminated union the turn route streams: `{ event, data }`, one per `event:`/`data:` frame. */
export type ConversationEvent = StreamBody<
  paths["/feature-requests/conversation/{id}/messages"]["post"]["responses"][200]
>;

/** The pipeline control room (ADR 0010): one snapshot, its rows, and the three facilitator actions. */
export type PipelineSnapshot = JsonBody<paths["/pipeline"]["get"]["responses"][200]>["data"];
export type PipelineIssue = PipelineSnapshot["issues"][number];
export type PipelineStage = PipelineIssue["stage"];
export type PipelinePullRequest = PipelineIssue["pullRequests"][number];
export type PipelineIssueShip = NonNullable<PipelineIssue["ship"]>;
export type PipelineEnvironment = PipelineSnapshot["environments"]["staging"];
export type PipelineShipRun = NonNullable<PipelineSnapshot["ship"]["run"]>;
export type DeployBody = JsonRequest<
  paths["/pipeline/issues/{number}/deploy-staging"]["post"]["requestBody"]
>;
export type DeployStagingResult = JsonBody<
  paths["/pipeline/issues/{number}/deploy-staging"]["post"]["responses"][200]
>["data"];
export type ShipBody = JsonRequest<paths["/pipeline/ship"]["post"]["requestBody"]>;
export type ShipRetryBody = JsonRequest<paths["/pipeline/ship/retry"]["post"]["requestBody"]>;
export type ShipResult = JsonBody<paths["/pipeline/ship"]["post"]["responses"][200]>["data"];
