import type { paths } from "./types";

/** The JSON body of a response object generated by openapi-typescript. */
export type JsonBody<R> = R extends { content: { "application/json": infer B } } ? B : never;
/** The JSON body of a request object generated by openapi-typescript. */
export type JsonRequest<R> =
  NonNullable<R> extends { content: { "application/json": infer B } } ? B : never;

export type ErrorEnvelope = JsonBody<paths["/auth/login"]["post"]["responses"][401]>;
export type ErrorBody = ErrorEnvelope["error"];
export type ErrorCode = ErrorBody["code"];

export type User = JsonBody<paths["/auth/me"]["get"]["responses"][200]>["data"]["user"];
export type AuthSession = JsonBody<paths["/auth/login"]["post"]["responses"][200]>["data"];
export type LoginBody = JsonRequest<paths["/auth/login"]["post"]["requestBody"]>;
export type RegisterBody = JsonRequest<paths["/auth/register"]["post"]["requestBody"]>;
